language: go
go:
  - 1.14.1
os:
  - linux
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_script:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go mod tidy
  - echo $DOCKERHUB_TOKEN | docker login --username madflojo --password-stdin
script:
  - gofmt -l ./ | grep -v vendor | wc -l | grep -q 0
  - go vet -v ./...
  - docker-compose -f dev-compose.yml up -d cassandra-primary cassandra redis
  - sleep 30
  - make tests
  - sleep 30
  - make bench
after_success:
  - goveralls -coverprofile=coverage/coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
