version: "3"
services:
  tests:
    build: .
    depends_on:
      - cassandra
      - cassandra-primary
    working_dir: /go/src/github.com/madflojo/hord
    entrypoint: go test -v ./...
  cassandra-primary:
    image: madflojo/cassandra:latest
    command: /bin/bash -c "sleep 1 && /docker-entrypoint.sh cassandra -f"
    environment:
      - CASSANDRA_KEYSPACE=hord
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
  cassandra:
    image: madflojo/cassandra:latest
    command: /bin/bash -c "sleep 15 && /docker-entrypoint.sh cassandra -f"
    environment:
      - CASSANDRA_SEEDS=cassandra-primary
      - CASSANDRA_KEYSPACE=hord
    depends_on:
      - cassandra-primary
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
