name: benchmarks

on:
  push:
    tags:
      - v*
    branches:
      - actions
      - main
  pull_request:
jobs:
  cassandra:
    runs-on: ubuntu-latest
    container: madflojo/ubuntu-build
    services:
      cassandra-primary:
        image: madflojo/cassandra:latest
        env:
          CASSANDRA_KEYSPACE: hord
        ports:
          - 7000
          - 7001
          - 7199
          - 9042
          - 9160

      cassandra:
        image: madflojo/cassandra:latest
        env:
          CASSANDRA_SEEDS: cassandra-primary
          CASSANDRA_KEYSPACE: hord
          SLEEP_TIMER: 15
        ports:
          - 7000
          - 7001
          - 7199
          - 9042
          - 9160
    steps:
    - uses: actions/checkout@v3
    # Using this instead of actions/setup-go to get around an issue with act
    - name: Install Go
      run: |
           curl -L https://go.dev/dl/go1.19.9.linux-amd64.tar.gz | tar -C /usr/local -xzf -
    - name: Execute Benchmarks
      run: |
        sleep 120
        /usr/local/go/bin/go test -run=Benchmark -bench "BenchmarkDrivers/Bench_Cassandra" ./...

  redis:
    runs-on: ubuntu-latest
    container: madflojo/ubuntu-build
    services:
      redis:
        image: bitnami/redis:latest
        env:
          ALLOW_EMPTY_PASSWORD: yes

      redis-sentinel:
        image: bitnami/redis-sentinel:latest
        env:
          REDIS_URL: redis://redis:6379
    steps:
    - uses: actions/checkout@v3
    # Using this instead of actions/setup-go to get around an issue with act
    - name: Install Go
      run: |
           curl -L https://go.dev/dl/go1.19.9.linux-amd64.tar.gz | tar -C /usr/local -xzf -
    - name: Execute Benchmarks
      run: |
        sleep 60
        /usr/local/go/bin/go test -run=Benchmark -bench "BenchmarkDrivers/Bench_Redis" ./...

  hashmap:
    runs-on: ubuntu-latest
    container: madflojo/ubuntu-build
    steps:
    - uses: actions/checkout@v3
    # Using this instead of actions/setup-go to get around an issue with act
    - name: Install Go
      run: |
           curl -L https://go.dev/dl/go1.19.9.linux-amd64.tar.gz | tar -C /usr/local -xzf -
    - name: Execute Benchmarks
      run: /usr/local/go/bin/go test -run=Benchmark -bench "BenchmarkDrivers/Bench_Hashmap" ./...

  boltdb:
    runs-on: ubuntu-latest
    container: madflojo/ubuntu-build
    steps:
    - uses: actions/checkout@v3
    # Using this instead of actions/setup-go to get around an issue with act
    - name: Install Go
      run: |
           curl -L https://go.dev/dl/go1.19.9.linux-amd64.tar.gz | tar -C /usr/local -xzf -
    - name: Execute Benchmarks
      run: /usr/local/go/bin/go test -run=Benchmark -bench "BenchmarkDrivers/Bench_BoltDB" ./...
