name: benchmarks

on:
  push:
    tags:
      - v*
    branches:
      - actions
      - main
  pull_request:
jobs:
  cassandra:
    runs-on: ubuntu-latest
    services:
      cassandra-primary:
        image: madflojo/cassandra:latest
        env:
          CASSANDRA_KEYSPACE: hord
        ports:
          - 7000
          - 7001
          - 7199
          - 9042
          - 9160

      cassandra:
        image: madflojo/cassandra:latest
        env:
          CASSANDRA_SEEDS: cassandra-primary
          CASSANDRA_KEYSPACE: hord
        ports:
          - 7000
          - 7001
          - 7199
          - 9042
          - 9160
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - name: Execute Tests
      run: go test -run=Benchmark -bench "BenchmarkDrivers/Bench_Cassandra" ./...

  redis:
    runs-on: ubuntu-latest
    services:
      redis:
        image: bitnami/redis:latest
        env:
          ALLOW_EMPTY_PASSWORD: yes

      redis-sentinel:
        image: bitnami/redis-sentinel:latest
        env:
          REDIS_URL: redis://redis:6379
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - name: Execute Tests
      run: go test -run=Benchmark -bench "BenchmarkDrivers/Bench_Redis" ./...
