name: tests

on:
  push:
    tags:
      - v*
    branches:
      - actions
      - main
  pull_request:
jobs:
  cassandra:
    runs-on: ubuntu-latest
    container: madflojo/ubuntu-build
    services:
      cassandra-primary:
        image: madflojo/cassandra:latest
        env:
          CASSANDRA_KEYSPACE: hord
        ports:
          - 7000
          - 7001
          - 7199
          - 9042
          - 9160

      cassandra:
        image: madflojo/cassandra:latest
        env:
          CASSANDRA_SEEDS: cassandra-primary
          CASSANDRA_KEYSPACE: hord
        ports:
          - 7000
          - 7001
          - 7199
          - 9042
          - 9160
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'
    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest
    - name: Execute Tests
      run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./drivers/cassandra
    - name: Update Coveralls
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=coverage.out -service=github

  redis:
    runs-on: ubuntu-latest
    container: madflojo/ubuntu-build
    services:
      redis:
        image: bitnami/redis:latest
        env:
          ALLOW_EMPTY_PASSWORD: yes

      redis-sentinel:
        image: bitnami/redis-sentinel:latest
        env:
          REDIS_URL: redis://redis:6379
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'
    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest
    - name: Execute Tests
      run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./drivers/cassandra
    - name: Update Coveralls
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=coverage.out -service=github
