name: tests

on:
  push:
    tags:
      - v*
    branches:
      - actions
      - main
  pull_request:
jobs:
  hord:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'
    - name: Execute Tests
      run: |
        go test -v -race -covermode=atomic -coverprofile=coverage.out .
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
    
  cassandra:
    runs-on: ubuntu-latest
    container: madflojo/ubuntu-build
    services:
      cassandra-primary:
        image: madflojo/cassandra:latest
        env:
          CASSANDRA_KEYSPACE: hord
        ports:
          - 7000
          - 7001
          - 7199
          - 9042
          - 9160

      cassandra:
        image: madflojo/cassandra:latest
        env:
          CASSANDRA_SEEDS: cassandra-primary
          CASSANDRA_KEYSPACE: hord
          SLEEP_TIMER: 15
        ports:
          - 7000
          - 7001
          - 7199
          - 9042
          - 9160
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'
    - name: Execute Tests
      run: |
        sleep 120 
        go test -v -race -covermode=atomic -coverprofile=coverage.out ./drivers/cassandra
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

  redis:
    runs-on: ubuntu-latest
    container: madflojo/ubuntu-build
    services:
      redis:
        image: bitnami/redis:latest
        env:
          ALLOW_EMPTY_PASSWORD: yes

      redis-sentinel:
        image: bitnami/redis-sentinel:latest
        env:
          REDIS_URL: redis://redis:6379
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'
    - name: Execute Tests
      run: |
        sleep 60
        go test -v -race -covermode=atomic -coverprofile=coverage.out ./drivers/redis
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

  mock:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'
    - name: Execute Tests
      run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./drivers/mock
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

  hashmap:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'
    - name: Execute Tests
      run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./drivers/hashmap
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

  boltdb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'
    - name: Execute Tests
      run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./drivers/bbolt
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
